services:
  # Application
  
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile

  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  # Utilities

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    entrypoint: [ "php", "/var/www/html/artisan" ]
    volumes:
      - ./src:/var/www/html
    
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    
  npm:
    image: node
    entrypoint: [ "npm" ]
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
