# docker-compose.yaml
version: '3'

services:
  registry:
    image: registry:2
    container_name: kubernetes-local-registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./data:/data
