services:
  # Application
  
  mysql:
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated

  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  # Utilities

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    entrypoint: [ "php", "/var/www/html/artisan" ]
    volumes:
      - ./src:/var/www/html
    
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    
  npm:
    image: node
    entrypoint: [ "npm" ]
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
