apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      name: users-app
      labels:
        app: users-app
    spec:
      containers:
        - name: users-app-container
          image: cc-users-api:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: AUTH_API_URL
              value: "auth-service.default"
      restartPolicy: Always
