services:
  frontend:
    build: ./frontend
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    networks:
      - goals-app
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - PORT=${NODE_APP_PORT}
    networks:
      - goals-app
    ports:
      - "${NODE_APP_PORT}:${NODE_APP_PORT}"
    depends_on:
      - mongo

  mongo:
    image: mongo
    networks:
      - goals-app
    volumes:
      - mongodb_data:/data/db

networks:
  goals-app:
    driver: bridge

volumes:
  mongodb_data:

