services:
  frontend:
    build: ./frontend
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    networks:
      - goals-app
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
      - PORT=${NODE_APP_PORT}
    networks:
      - goals-app
    ports:
      - "${NODE_APP_PORT}:${NODE_APP_PORT}"
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./backend:/app
      - node_app_data:/app/logs


  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - goals-app
    volumes:
      - mongodb_data:/data/db

networks:
  goals-app:
    driver: bridge

volumes:
  mongodb_data:
  node_app_data:

